# Paso a paso

In [ ]:
import pandas as pd

datos = pd.read_excel('/content/5_Violencia_interpersonal_Colombia_2022.xlsx', sheet_name="DEPARTAMENTO Y MUNICIPIO")
# Eliminar las últimas 6 filas
datos = datos.iloc[:-7]

In [ ]:
datos

,DIVIPOLA,COMPORTAMIENTO DE LAS LESIONES NO FATALES POR VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO 2022\n\nCASOS Y TASAS X 100.00 HABITANTES,VIOLENCIA INTERPERSONAL (CASOS),VIOLENCIA INTERPERSONAL (CASOS).1,VIOLENCIA INTERPERSONAL (CASOS).2,VIOLENCIA INTERPERSONAL (CASOS).3,VIOLENCIA INTERPERSONAL (CASOS).4,VIOLENCIA INTERPERSONAL (CASOS).5,VIOLENCIA INTERPERSONAL (CASOS).6,VIOLENCIA INTERPERSONAL (TASAS),VIOLENCIA INTERPERSONAL (TASAS).1,VIOLENCIA INTERPERSONAL (TASAS).2,VIOLENCIA INTERPERSONAL (TASAS).3,VIOLENCIA INTERPERSONAL (TASAS).4,VIOLENCIA INTERPERSONAL (TASAS).5,VIOLENCIA INTERPERSONAL (TASAS).6
0,CÓDIGOS,SEXO,Hombre,Hombre,HOMBRE,Mujer,Mujer,MUJER,TOTAL,Hombre (Tasa x 100.000 Hab.),Hombre (Tasa x 100.000 Hab.),HOMBRE (TASA X 100.000 HAB.),Mujer (Tasa x 100.000 Hab.),Mujer (Tasa x 100.000 Hab.),MUJER (TASA X 100.000 HAB.),TOTAL
1,N°,DEPARTAMENTO Y MUNICIPIO DEL HECHO DANE / MAYO...,Menores de Edad (<18 años),Mayores de Edad (>18 años),TOTAL,Menores de Edad (<18 años),Mayores de Edad (>18 años),TOTAL,NaN,Menores de Edad (<18 años),Mayores de Edad (>18 años),TOTAL,Menores de Edad (<18 años),Mayores de Edad (>18 años),TOTAL,(TASA X 100.000 HAB.)
2,91,Amazonas,11,97,108,8,54,62,170,61.992786,384.417231,251.297205,47.469293,226.320201,152.285511,203.130601
3,91405,La Chorrera,-,1,1,-,-,-,1,0,119.904077,57.803468,0,0,0,32.113038
4,91001,Leticia,11,96,107,8,54,62,169,104.503135,585.651537,397.503529,79.325731,333.374491,235.893924,317.663202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1064,97511,Pacoa,1,-,1,-,-,-,1,75.930144,0,41.876047,0,0,0,21.867483
1065,97666,Taraira,-,3,3,-,-,-,3,0,494.233937,235.478807,0,0,0,120.918984
1066,99,Vichada,2,12,14,-,8,8,22,7.739938,32.042724,22.120398,0,24.219672,13.876362,18.190538
1067,99001,Puerto Carreño,2,12,14,-,8,8,22,54.945055,158.457679,124.855079,0,111.095681,75.082121,100.603622
1068,999,Sin información,-,4,4,-,-,-,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Limpieza de datos

In [ ]:
import pandas as pd

# Inicializar una lista para las columnas a eliminar
cols_to_drop = []

# Iterar sobre las columnas del DataFrame
for col in datos.columns:
    # Convertir los valores de la columna a texto
    col_values = datos[col].astype(str)

    # Verificar si "TOTAL" está en alguna celda de la columna
    if col_values.str.contains('TOTAL', case=False, na=False).any():
        cols_to_drop.append(col)

# Eliminar las columnas identificadas
datos_cleaned = datos.drop(columns=cols_to_drop)

# Lista de nombres para eliminar
nombres_a_eliminar = [
    "Amazonas", "Antioquia", "Arauca", "Archipiélago de San Andrés, Providencia y Santa Catalina",
    "Atlántico", "Bogotá, D.C.", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca",
    "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira",
    "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Santander",
    "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada"
]

# Inicializar una lista para las filas a eliminar
indices_a_eliminar = []

# Iterar sobre las filas del DataFrame
for i in range(len(datos_cleaned)):
    # Verificar si alguna celda en la columna 2 contiene un nombre a eliminar
    if datos_cleaned.iloc[i, 1] in nombres_a_eliminar:
        indices_a_eliminar.append(i)

# Eliminar las filas identificadas
datos_cleaned = datos_cleaned.drop(indices_a_eliminar).reset_index(drop=True)

# Eliminar las últimas 4 columnas
datos_cleaned = datos_cleaned.iloc[:, :-4]

# Reiniciar el índice
datos_cleaned.reset_index(drop=True, inplace=True)

# Establecer la primera fila como los nombres de las columnas
datos_cleaned.columns = datos_cleaned.iloc[0]  # Establece la primera fila como encabezado
datos_cleaned = datos_cleaned[1:]  # Elimina la primera fila del DataFrame
datos_cleaned.reset_index(drop=True, inplace=True)  # Reiniciar el índice

# Crear DataFrames para las columnas específicas
hombre = datos_cleaned.iloc[:, [0, 1, 2, 3]]  # Columnas 0, 1, 2
hombre.columns = hombre.iloc[0]
mujer = datos_cleaned.iloc[:, [0, 1, 4, 5]]  # Columnas 0, 3, 4
mujer.columns = mujer.iloc[0]
hombre = hombre[1:]
mujer = mujer[1:]

# Cambiar el nombre de la columna "N°" a "Divipola"
hombre.rename(columns={"N°": "Divipola"}, inplace=True)
mujer.rename(columns={"N°": "Divipola"}, inplace=True)

#Cambiar nombre Municipio
hombre.rename(columns={"DEPARTAMENTO Y MUNICIPIO DEL HECHO DANE / MAYOR DE EDAD (> 18 AÑOS) O MENOR DE EDAD (< 18 AÑOS)": "Municipio"}, inplace=True)
mujer.rename(columns={"DEPARTAMENTO Y MUNICIPIO DEL HECHO DANE / MAYOR DE EDAD (> 18 AÑOS) O MENOR DE EDAD (< 18 AÑOS)": "Municipio"}, inplace=True)

In [ ]:
mujer

,Divipola,Municipio,Menores de Edad (<18 años),Mayores de Edad (>18 años)
1,91405,La Chorrera,-,-
2,91001,Leticia,8,54
3,5002,Abejorral,-,15
4,5021,Alejandría,-,-
5,5030,Amagá,5,15
...,...,...,...,...
1014,97001,Mitú,4,21
1015,97511,Pacoa,-,-
1016,97666,Taraira,-,-
1017,99001,Puerto Carreño,-,8
1018,999,Sin información,-,-

## Anulación de dinamización de columnas

In [ ]:
# Función para combinar las columnas de edad en un formato deseado
def reshape_age_columns(df):
    # Crear una lista para almacenar las filas nuevas
    new_rows = []

    # Iterar sobre cada fila del DataFrame original
    for _, row in df.iterrows():
        # Iterar sobre las columnas de edad
        for col in ['Menores de Edad (<18 años)', 'Mayores de Edad (>18 años)']:
            if pd.notna(row[col]):  # Verificar si el valor no es NaN
                new_row = {
                    'Divipola': row['Divipola'],  # Mantener el valor de 'Divipola'
                    'Municipio': row['Municipio'],  # Mantener el nombre
                    'Edad': col,  # El nombre de la columna original
                    'Casos': row[col]  # El valor de la columna actual para 'Casos'
                }
                new_rows.append(new_row)

    # Crear un nuevo DataFrame con las filas transformadas
    df_reshaped = pd.DataFrame(new_rows)

    return df_reshaped

# Aplicar la función al DataFrame
hombre = reshape_age_columns(hombre)
mujer = reshape_age_columns(mujer)

## Unir dfs

In [ ]:
# Agregar una nueva columna 'Género' con el valor constante 'hombre' o 'mujer'
hombre['Género'] = 'hombre'
mujer['Género'] = 'mujer'

In [ ]:
# Unir los DataFrames `hombre` y `mujer` verticalmente
data_unida = pd.concat([hombre, mujer], ignore_index=True)
data_unida["Año"] = 2022

In [ ]:
data_unida

,Divipola,Municipio,Edad,Casos,Género,Año
0,91405,La Chorrera,Menores de Edad (<18 años),-,hombre,2022
1,91405,La Chorrera,Mayores de Edad (>18 años),1,hombre,2022
2,91001,Leticia,Menores de Edad (<18 años),11,hombre,2022
3,91001,Leticia,Mayores de Edad (>18 años),96,hombre,2022
4,5002,Abejorral,Menores de Edad (<18 años),1,hombre,2022
...,...,...,...,...,...,...
4067,97666,Taraira,Mayores de Edad (>18 años),-,mujer,2022
4068,99001,Puerto Carreño,Menores de Edad (<18 años),-,mujer,2022
4069,99001,Puerto Carreño,Mayores de Edad (>18 años),8,mujer,2022
4070,999,Sin información,Menores de Edad (<18 años),-,mujer,2022
4071,999,Sin información,Mayores de Edad (>18 años),-,mujer,2022

# Para 2019 a 2022

In [ ]:
import pandas as pd

años = [2019, 2020, 2021, 2022]
data_f = []

for año in años:
    # Leer el archivo Excel
    datos = pd.read_excel(f'/content/5-Violencia interpersonal. Colombia, {año}.xlsx', sheet_name="DEPARTAMENTO Y MUNICIPIO")

    # Eliminar las últimas 7 filas
    datos = datos.iloc[:-7]

    # Inicializar una lista para las columnas a eliminar
    cols_to_drop = []
    for col in datos.columns:
        col_values = datos[col].astype(str)
        if col_values.str.contains('TOTAL', case=False, na=False).any():
            cols_to_drop.append(col)

    # Eliminar las columnas identificadas
    datos_cleaned = datos.drop(columns=cols_to_drop)

    # Lista de nombres para eliminar
    nombres_a_eliminar = [
        "Amazonas", "Antioquia", "Arauca", "Archipiélago de San Andrés, Providencia y Santa Catalina",
        "Atlántico", "Bogotá, D.C.", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca",
        "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira",
        "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Santander",
        "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada"
    ]

    # Filtrar filas que contienen nombres a eliminar en cualquier celda
    datos_cleaned = datos_cleaned[~datos_cleaned.apply(lambda row: row.astype(str).isin(nombres_a_eliminar).any(), axis=1)]

    # Eliminar las últimas 4 columnas
    datos_cleaned = datos_cleaned.iloc[:, :-4]

    # Establecer la primera fila como los nombres de las columnas
    datos_cleaned.columns = datos_cleaned.iloc[0]
    datos_cleaned = datos_cleaned[1:]
    datos_cleaned.reset_index(drop=True, inplace=True)

    # Crear DataFrames para las columnas específicas
    hombre = datos_cleaned.iloc[:, [0, 1, 2, 3]]  # Columnas 0, 1, 2, 3
    hombre.columns = hombre.iloc[0]
    hombre = hombre[1:]
    hombre.reset_index(drop=True, inplace=True)

    mujer = datos_cleaned.iloc[:, [0, 1, 4, 5]]  # Columnas 0, 1, 4, 5
    mujer.columns = mujer.iloc[0]
    mujer = mujer[1:]
    mujer.reset_index(drop=True, inplace=True)

    # Cambiar el nombre de las columnas
    hombre.rename(columns={"N°": "Divipola"}, inplace=True)
    mujer.rename(columns={"N°": "Divipola"}, inplace=True)
    hombre.rename(columns={"DEPARTAMENTO Y MUNICIPIO DEL HECHO DANE / MAYOR DE EDAD (> 18 AÑOS) O MENOR DE EDAD (< 18 AÑOS)": "Municipio"}, inplace=True)
    mujer.rename(columns={"DEPARTAMENTO Y MUNICIPIO DEL HECHO DANE / MAYOR DE EDAD (> 18 AÑOS) O MENOR DE EDAD (< 18 AÑOS)": "Municipio"}, inplace=True)

    # Función para combinar las columnas de edad en un formato deseado
    def reshape_age_columns(df):
        new_rows = []
        for _, row in df.iterrows():
            for col in ['Menores de Edad (<18 años)', 'Mayores de Edad (>18 años)']:
                if pd.notna(row[col]):
                    new_row = {
                        'Divipola': row['Divipola'],
                        'Municipio': row['Municipio'],
                        'Edad': col,
                        'Casos': row[col]
                    }
                    new_rows.append(new_row)
        return pd.DataFrame(new_rows)

    # Aplicar la función a los DataFrames
    hombre = reshape_age_columns(hombre)
    mujer = reshape_age_columns(mujer)

    # Agregar una nueva columna 'Género'
    hombre['Género'] = 'hombre'
    mujer['Género'] = 'mujer'

    # Unir los DataFrames `hombre` y `mujer`
    data_unida = pd.concat([hombre, mujer], ignore_index=True)
    data_unida["Año"] = año

    # Añadir el DataFrame del año a la lista
    data_f.append(data_unida)

# Concatenar todos los DataFrames en la lista
data_final_2019_2022 = pd.concat(data_f, ignore_index=True)


# Opcional: Guardar el DataFrame final en un archivo Excel
data_final_2019_2022.to_excel('/content/data_final_2019_2022.xlsx', index=False)

# Año 2016

In [ ]:
import pandas as pd

# Leer el archivo Excel
datos = pd.read_excel(f'/content/5-Violencia interpersonal. Colombia, 2016.xlsx', sheet_name="DEPARTAMENTO Y MUNICIPIO")

# Eliminar las últimas 7 filas
datos = datos.iloc[:-5]

# Inicializar una lista para las columnas a eliminar
cols_to_drop = []
for col in datos.columns:
    col_values = datos[col].astype(str)
    if col_values.str.contains('TOTAL', case=False, na=False).any():
        cols_to_drop.append(col)

# Eliminar las columnas identificadas
datos_cleaned = datos.drop(columns=cols_to_drop)

# Lista de nombres para eliminar
nombres_a_eliminar = [
    "Amazonas", "Antioquia", "Arauca", "Archipiélago de San Andrés, Providencia y Santa Catalina",
    "Atlántico", "Bogotá, D.C.", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca",
    "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira",
    "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Santander",
    "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada"
]

# Filtrar filas que contienen nombres a eliminar en cualquier celda
datos_cleaned = datos_cleaned[~datos_cleaned.apply(lambda row: row.astype(str).isin(nombres_a_eliminar).any(), axis=1)]
datos_cleaned.reset_index(drop=True, inplace=True)

# Crear DataFrames para las columnas específicas
hombre = datos_cleaned.iloc[:, [0, 1, 2]]  # Columnas 0, 1, 2, 3
hombre.reset_index(drop=True, inplace=True)
hombre = hombre[1:]

mujer = datos_cleaned.iloc[:, [0, 1, 4]]  # Columnas 0, 1, 4, 5
mujer.reset_index(drop=True, inplace=True)
mujer = mujer[1:]

#Cambiar nombre a columna 2
hombre.rename(columns={"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO 2016 / SEXO, DEPARTAMENTO, MUNICIPIO DEL HECHO, NÚMERO DE CASOS Y TASAS POR 100.000 HABITANTES": "Municipio"}, inplace=True)
mujer.rename(columns={"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO 2016 / SEXO, DEPARTAMENTO, MUNICIPIO DEL HECHO, NÚMERO DE CASOS Y TASAS POR 100.000 HABITANTES": "Municipio"}, inplace=True)

#Cambiar nombre 3ra columna
hombre.rename(columns={"Hombre": "Casos"}, inplace=True)
mujer.rename(columns={"Mujer": "Casos"}, inplace=True)

# Cambiar el nombre 1ra columna
hombre.rename(columns={"CÓDIGOS DIVIPOLA": "Divipola"}, inplace=True)
mujer.rename(columns={"CÓDIGOS DIVIPOLA": "Divipola"}, inplace=True)

#Añadir columna sexo
hombre['Género'] = 'hombre'
mujer['Género'] = 'mujer'

# Unir los DataFrames `hombre` y `mujer`
data_unida = pd.concat([hombre, mujer], ignore_index=True)
data_unida["Año"] = 2016

data_2016 = data_unida

# Opcional: Guardar el DataFrame final en un archivo Excel
data_2016.to_excel('/content/data_2016.xlsx', index=False)

# Años 2017 y 2018

In [ ]:
for año in [2017, 2018]:
  # Leer el archivo Excel
  datos = pd.read_excel(f'/content/5-Violencia interpersonal. Colombia, {año}.xlsx', sheet_name="DEPARTAMENTO Y MUNICIPIO")
  # Eliminar las últimas 7 filas
  datos = datos.iloc[1:-7, :-2]

  # Lista de nombres para eliminar
  nombres_a_eliminar = [
      "Amazonas", "Antioquia", "Arauca", "Archipiélago de San Andrés, Providencia y Santa Catalina",
      "Atlántico", "Bogotá, D.C.", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca",
      "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira",
      "Magdalena", "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Santander",
      "Sucre", "Tolima", "Valle del Cauca", "Vaupés", "Vichada"
  ]

  # Filtrar filas que contienen nombres a eliminar en cualquier celda
  datos_cleaned = datos[~datos.apply(lambda row: row.astype(str).isin(nombres_a_eliminar).any(), axis=1)]
  datos_cleaned.reset_index(drop=True, inplace=True)

  # Crear DataFrames para las columnas específicas
  hombre = datos_cleaned.iloc[:, [0, 1, 2]]  # Columnas 0, 1, 2, 3
  hombre.reset_index(drop=True, inplace=True)

  mujer = datos_cleaned.iloc[:, [0, 1, 4]]  # Columnas 0, 1, 4, 5
  mujer.reset_index(drop=True, inplace=True)

  #Cambiar nombre a columna 2
  hombre.rename(columns={f"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO {año} / DEPARTAMENTO, MUNICIPIO DEL HECHO DANE": "Municipio"}, inplace=True)
  mujer.rename(columns={f"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO {año} / DEPARTAMENTO, MUNICIPIO DEL HECHO DANE": "Municipio"}, inplace=True)

  #Cambiar nombre 3ra columna
  hombre.rename(columns={"VIOLENCIA INTERPERSONAL": "Casos"}, inplace=True)
  mujer.rename(columns={"VIOLENCIA INTERPERSONAL.2": "Casos"}, inplace=True)

  # Cambiar el nombre de la primera columna a 'Divipola'
  hombre.rename(columns={hombre.columns[0]: "Divipola"}, inplace=True)
  mujer.rename(columns={mujer.columns[0]: "Divipola"}, inplace=True)

  # Unir los DataFrames `hombre` y `mujer`
  data_unida = pd.concat([hombre, mujer], ignore_index=True)
  data_unida["Año"] = año

  data_2017_2018 = data_unida

<ipython-input-98-1659d7f5784b>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hombre.rename(columns={f"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO {año} / DEPARTAMENTO, MUNICIPIO DEL HECHO DANE": "Municipio"}, inplace=True)
<ipython-input-98-1659d7f5784b>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mujer.rename(columns={f"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO {año} / DEPARTAMENTO, MUNICIPIO DEL HECHO DANE": "Municipio"}, inplace=True)
<ipython-input-98-1659d7f5784b>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hombre.rename(columns={"VIOLENCIA INTERPERSONAL": "Casos"}, inplace=True)
<ipython-input-98-1659d7f5784b>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mujer.rename(columns={"VIOLENCIA INTERPERSONAL.2": "Casos"}, inplace=True)
<ipython-input-98-1659d7f5784b>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hombre.rename(columns={hombre.columns[0]: "Divipola"}, inplace=True)
<ipython-input-98-1659d7f5784b>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mujer.rename(columns={mujer.columns[0]: "Divipola"}, inplace=True)
<ipython-input-98-1659d7f5784b>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hombre.rename(columns={f"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO {año} / DEPARTAMENTO, MUNICIPIO DEL HECHO DANE": "Municipio"}, inplace=True)
<ipython-input-98-1659d7f5784b>:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mujer.rename(columns={f"VIOLENCIA INTERPERSONAL EN COLOMBIA AÑO {año} / DEPARTAMENTO, MUNICIPIO DEL HECHO DANE": "Municipio"}, inplace=True)
<ipython-input-98-1659d7f5784b>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hombre.rename(columns={"VIOLENCIA INTERPERSONAL": "Casos"}, inplace=True)
<ipython-input-98-1659d7f5784b>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mujer.rename(columns={"VIOLENCIA INTERPERSONAL.2": "Casos"}, inplace=True)
<ipython-input-98-1659d7f5784b>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hombre.rename(columns={hombre.columns[0]: "Divipola"}, inplace=True)
<ipython-input-98-1659d7f5784b>:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mujer.rename(columns={mujer.columns[0]: "Divipola"}, inplace=True)

# Concatenar de 2016 a 2018

In [ ]:
data_final_2016_2018 = pd.concat([data_2016, data_2017_2018], ignore_index=True)

#Guardar en Excel
data_final_2016_2018.to_excel('/content/data_final_2016_2018.xlsx', index=False)

In [ ]:
data_final_2016_2018

     Divipola        Municipio Casos  Género   Año
0       91263       El Encanto     1  hombre  2016
1       91405      La Chorrera     3  hombre  2016
2       91407       La Pedrera     1  hombre  2016
3       91001          Leticia   171  hombre  2016
4       91540    Puerto Nariño     2  hombre  2016
...       ...              ...   ...     ...   ...
4095    97001             Mitú     -     NaN  2018
4096    99773         Cumaribo     -     NaN  2018
4097    99524     La Primavera     -     NaN  2018
4098    99001   Puerto Carreño     -     NaN  2018
4099      999  Sin información     9     NaN  2018

[4100 rows x 5 columns]

# Conglomerado 2016-1022 SIN EDAD

In [ ]:
data_final_conglomerado = pd.concat([data_final_2019_2022, data_final_2016_2018], ignore_index=True)

#Guardar en Excel
data_final_conglomerado.to_excel('/content/data_final.xlsx', index=False)